image:
  file: .gitpod.Dockerfile

tasks:
  - name: taskman application
    command: projen dev
  - name: Redis
    command: redis-server

ports:
    - name: Backend
      port: 8000
      onOpen: open-browser
    
github:
    prebuilds:
        master: true
        pullRequests: false
        addComment: false