name: Hello World

on:
  pull_request:
    types: [opened]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install pylint
        run: pip install pylint
      - name: Run pylint
        run: pylint taskman
